SELECT A.DEPT_ID AS DEPT_ID, A.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(B.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT A JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
GROUP BY DEPT_ID
ORDER BY ROUND(AVG(B.SAL)) DESC;

